export const GET_GITHUB_USERS_SEARCH_DATA = "GET_GITHUB_USERS_SEARCH_DATA";
export const GET_GITHUB_USER_DATA = "GET_GITHUB_USER_DATA";
export const GET_USER_REPO_DATA = "GET_USER_REPO_DATA";

export const GET_AFFECTED_COUNTRY_LIST = "GET_AFFECTED_COUNTRY_LIST";
export const GET_ACTIVE_CASES_LIST = "GET_ACTIVE_CASES_LIST";
export const GET_CONFIRMED_CASES_LIST = "GET_CONFIRMED_CASES_LIST";

export const GET_EXPRESSION_DATA = "GET_EXPRESSION_DATA";
