export const CB_CREATE_LEAF_NODE = "CB_CREATE_LEAF_NODE";
export const CB_CREATE_OPERATOR_NODE = "CB_CREATE_OPERATOR_NODE";
export const CB_CREATE_FUNCTION_NODE = "CB_CREATE_FUNCTION_NODE";
export const CB_CREATE_SAVED_DATAPOINT_NODE = "CB_CREATE_SAVED_DATAPOINT_NODE";
export const CB_MERGE_SELECTED_NODE = "CB_MERGE_SELECTED_NODE";
export const CB_SPLIT_SELECTED_NODE = "CB_SPLIT_SELECTED_NODE";
export const CB_SPLIT_SELECTED_OP_NODE = "CB_SPLIT_SELECTED_OP_NODE";
export const CB_TOGGLE_SELECTED_NODE = "CB_TOGGLE_SELECTED_NODE";
export const CB_SELECT_ALL_NODES = "CB_SELECT_ALL_NODES";
export const CB_SELECT_ALL_NODES_BY_TYPE = "CB_SELECT_ALL_NODES_BY_TYPE";
export const CB_REMOVE_ALL_NODES = "CB_REMOVE_ALL_NODES";
export const CB_CLEAR_CODING_BOX = "CB_CLEAR_CODING_BOX";
export const CB_REMOVE_NODES_BY_ID = "CB_REMOVE_NODES_BY_ID";
export const CB_REMOVE_SELECTED_NODES = "CB_REMOVE_SELECTED_NODES";
export const CB_SELECT_ALL_OPERATORS = "CB_SELECT_ALL_OPERATORS";
export const CB_CHANGE_SELECTED_OPERATORS = "CB_CHANGE_SELECTED_OPERATORS";
export const CB_CHANGE_SELECTED_OPERATOR_BY_ID =
  "CB_CHANGE_SELECTED_OPERATOR_BY_ID";
export const CB_DUPLICATE_SELECTED_NODES = "CB_DUPLICATE_SELECTED_NODES";
export const CB_COPY_SELECTED_NODES = "CB_COPY_SELECTED_NODES";
export const CB_PASTE_COPIED_NODES = "CB_PASTE_COPIED_NODES";
export const CB_SET_OVERRIDE_LABEL_BY_ID = "CB_SET_OVERRIDE_LABEL_BY_ID";
export const CB_REMOVE_FUNCTION_NODE_BY_ID = "CB_REMOVE_FUNCTION_NODE_BY_ID";
export const CB_CHANGE_FUNCTION_OF_SELECTED_NODES =
  "CB_CHANGE_FUNCTION_OF_SELECTED_NODES";
export const CB_SELECT_ALL_FUNCTION = "CB_SELECT_ALL_FUNCTION";
export const CB_SELECT_FUNCTION_BY_ID = "CB_SELECT_FUNCTION_BY_ID";
export const CB_CHANGE_SELECTED_FUNCTION_NODES =
  "CB_CHANGE_SELECTED_FUNCTION_NODES";
export const CB_MERGE_OPERATOR_TEXT = "CB_MERGE_OPERATOR_TEXT";
export const CB_SELECTED_LABEL_TYPE = "CB_SELECTED_LABEL_TYPE";
export const CB_INSERT_NODES = "CB_INSERT_NODES";
